# Generated by Django 2.2.2 on 2019-06-09 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(default=datetime.date(2020, 3, 14)),
        ),
    ]
